spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
#  h2:
#    console:
#      enabled: true
#  sql:
#    init:
#      data-locations: classpath:dummy-data.sql
#      mode: always
#      platform: h2

datasource:
  db:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: admin
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true